var html_s1 = document.getElementById("html_s1").innerHTML;
var html_s2 = document.getElementById("html_s2").innerHTML;
var html_s3 = document.getElementById("html_s3").innerHTML;
var html_s4 = document.getElementById("html_s4").innerHTML;
var html_s5 = document.getElementById("html_s5").innerHTML;
var html_s6 = document.getElementById("html_s6").innerHTML;
var html_s7 = document.getElementById("html_s7").innerHTML;
var html_s8 = document.getElementById("html_s8").innerHTML;
var html_s9 = document.getElementById("html_s9").innerHTML;
var html_s10 = document.getElementById("html_s10").innerHTML;
var html_s11 = document.getElementById("html_s11").innerHTML;
var html_s12 = document.getElementById("html_s12").innerHTML;
var html_s13 = document.getElementById("html_s13").innerHTML;
var html_s14 = document.getElementById("html_s14").innerHTML;
var html_s15 = document.getElementById("html_s15").innerHTML;
var html_s16 = document.getElementById("html_s16").innerHTML;
var html_s17 = document.getElementById("html_s17").innerHTML;
var html_s18 = document.getElementById("html_s18").innerHTML;
var html_s19 = document.getElementById("html_s19").innerHTML;
var html_s20 = document.getElementById("html_s20").innerHTML;
var html_s21 = document.getElementById("html_s21").innerHTML;
var html_s22 = document.getElementById("html_s22").innerHTML;
var html_s23 = document.getElementById("html_s23").innerHTML;
var html_s24 = document.getElementById("html_s24").innerHTML;
var html_s25 = document.getElementById("html_s25").innerHTML;
var html_s26 = document.getElementById("html_s26").innerHTML;
var html_s27 = document.getElementById("html_s27").innerHTML;
var html_s28 = document.getElementById("html_s28").innerHTML;
var html_s29 = document.getElementById("html_s29").innerHTML;
var html_s30 = document.getElementById("html_s30").innerHTML;
//
var alt_html_s1 = document.getElementById("alt_html_s1").innerHTML;
var alt_html_s2 = document.getElementById("alt_html_s2").innerHTML;
var alt_html_s3 = document.getElementById("alt_html_s3").innerHTML;
var alt_html_s4 = document.getElementById("alt_html_s4").innerHTML;
var alt_html_s5 = document.getElementById("alt_html_s5").innerHTML;
var alt_html_s6 = document.getElementById("alt_html_s6").innerHTML;
var alt_html_s7 = document.getElementById("alt_html_s7").innerHTML;
var alt_html_s8 = document.getElementById("alt_html_s8").innerHTML;
var alt_html_s9 = document.getElementById("alt_html_s9").innerHTML;
var alt_html_s10 = document.getElementById("alt_html_s10").innerHTML;
var alt_html_s11 = document.getElementById("alt_html_s11").innerHTML;
var alt_html_s12 = document.getElementById("alt_html_s12").innerHTML;
var alt_html_s13 = document.getElementById("alt_html_s13").innerHTML;
var alt_html_s14 = document.getElementById("alt_html_s14").innerHTML;
var alt_html_s15 = document.getElementById("alt_html_s15").innerHTML;
var alt_html_s16 = document.getElementById("alt_html_s16").innerHTML;
var alt_html_s17 = document.getElementById("alt_html_s17").innerHTML;
var alt_html_s18 = document.getElementById("alt_html_s18").innerHTML;
var alt_html_s19 = document.getElementById("alt_html_s19").innerHTML;
var alt_html_s20 = document.getElementById("alt_html_s20").innerHTML;
var alt_html_s21 = document.getElementById("alt_html_s21").innerHTML;
var alt_html_s22 = document.getElementById("alt_html_s22").innerHTML;
var alt_html_s23 = document.getElementById("alt_html_s23").innerHTML;
var alt_html_s24 = document.getElementById("alt_html_s24").innerHTML;
var alt_html_s25 = document.getElementById("alt_html_s25").innerHTML;
var alt_html_s26 = document.getElementById("alt_html_s26").innerHTML;
var alt_html_s27 = document.getElementById("alt_html_s27").innerHTML;
var alt_html_s28 = document.getElementById("alt_html_s28").innerHTML;
var alt_html_s29 = document.getElementById("alt_html_s29").innerHTML;
var alt_html_s30 = document.getElementById("alt_html_s30").innerHTML;

var html1 = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta content="width=device-width, initial-scale=1" name="viewport"><title>NTTTOON</title><link href="https://fonts.googleapis.com/css?family=Noto+Serif:400,700&display=swap&subset=vietnamese" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css" rel="stylesheet">';
var html_css = '<style>body,html{margin:0}html{overflow-x:hidden}p{font-family:"Noto Serif",serif;line-height:1.5;color:#000;font-size:18px}.mg-image{max-width:100%;height:auto}.mg-bar:after,.mg-bar:before,.mg-cell-row:after,.mg-cell-row:before,.mg-clear:after,.mg-clear:before,.mg-container:after,.mg-container:before,.mg-panel:after,.mg-panel:before,.mg-row-padding:after,.mg-row-padding:before,.mg-row:after,.mg-row:before{content:"";display:table;clear:both}.mg-col,.mg-half,.mg-quarter,.mg-third,.mg-threequarter,.mg-twothird{float:left;width:100%}.mg-col.s1{width:8.33333%}.mg-col.s2{width:16.66666%}.mg-col.s3{width:24.99999%}.mg-col.s4{width:33.33333%}.mg-col.s5{width:41.66666%}.mg-col.s6{width:49.99999%}.mg-col.s7{width:58.33333%}.mg-col.s8{width:66.66666%}.mg-col.s9{width:74.99999%}.mg-col.s10{width:83.33333%}.mg-col.s11{width:91.66666%}.mg-col.s12{width:99.99999%}@media (min-width:601px){.mg-col.m1{width:8.33333%}.mg-col.m2{width:16.66666%}.mg-col.m3,.mg-quarter{width:24.99999%}.mg-col.m4,.mg-third{width:33.33333%}.mg-col.m5{width:41.66666%}.mg-col.m6,.mg-half{width:49.99999%}.mg-col.m7{width:58.33333%}.mg-col.m8,.mg-twothird{width:66.66666%}.mg-col.m9,.mg-threequarter{width:74.99999%}.mg-col.m10{width:83.33333%}.mg-col.m11{width:91.66666%}.mg-col.m12{width:99.99999%}}@media (min-width:993px){.mg-col.l1{width:8.33333%}.mg-col.l2{width:16.66666%}.mg-col.l3{width:24.99999%}.mg-col.l4{width:33.33333%}.mg-col.l5{width:41.66666%}.mg-col.l6{width:49.99999%}.mg-col.l7{width:58.33333%}.mg-col.l8{width:66.66666%}.mg-col.l9{width:74.99999%}.mg-col.l10{width:83.33333%}.mg-col.l11{width:91.66666%}.mg-col.l12{width:99.99999%}}.mg-content,.mg-content600{max-width:980px;margin-left:auto;margin-right:auto}.mg-content600{max-width:600px}.mg-h1title{font-size:48px!important;line-height:1.2}@media (max-width:600px){.mg-hide-small{display:none!important}}@media (min-width:993px){.mg-hide-large{display:none!important}}@media (max-width:992px) and (min-width:601px){.mg-hide-medium{display:none!important}}.mg-bottom,.mg-top{position:fixed;width:100%;z-index:1}.mg-top{top:0}.mg-bottom{bottom:0}.mg-row-padding,.mg-row-padding>.mg-col,.mg-row-padding>.mg-half,.mg-row-padding>.mg-quarter,.mg-row-padding>.mg-third,.mg-row-padding>.mg-threequarter,.mg-row-padding>.mg-twothird{padding:0 8px}.mg-container{padding:.01em 16px}.mg-left-align{text-align:left!important}.mg-right-align{text-align:right!important}.mg-justify{text-align:justify!important}.mg-center{text-align:center!important}.mg-padding-small{padding:4px 8px!important}.mg-padding{padding:8px 16px!important}.mg-padding-large{padding:12px 24px!important}.mg-padding-16{padding-top:16px!important;padding-bottom:16px!important}.mg-padding-24{padding-top:24px!important;padding-bottom:24px!important}.mg-padding-32{padding-top:32px!important;padding-bottom:32px!important}.mg-padding-48{padding-top:48px!important;padding-bottom:48px!important}.mg-padding-64{padding-top:64px!important;padding-bottom:64px!important}.mg-left{float:left!important}.mg-right{float:right!important}.mg-top-spacing{margin-top:67px}.mg-dropcap{float:left;padding:8px 8px 0 0;font-size:100px;line-height:30px}.mg-video-responsive{position:relative;padding-bottom:56.25%;padding-top:30px;height:0;overflow:hidden}.mg-video-responsive iframe,video{position:absolute;top:0;left:0;width:100%;height:100%}</style></head><body>';
var html_evatop = '<div id="cssipad"></div><div class="mg-top-spacing"></div>';

var slidescript ='<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script><script>new WOW().init();</script><script>if(window.screen.availWidth == 768 || window.screen.availWidth == 1366){document.getElementById("cssipad").innerHTML = "<style>#content-mgz{width:100%}.heading-site a{font-size:34px}</style>"}';

var html = html1 + html_css +html_evatop + html_s1 + html_s2 + html_s3 + html_s4 + html_s5 + html_s6 + html_s7 + html_s8 + html_s9 + html_s10 + html_s11 + html_s12 + html_s13 + html_s14 + html_s15 + html_s16 + html_s17 + html_s18 + html_s19 + html_s20 + html_s21 + html_s22 + html_s23 + html_s24 + html_s25 + html_s26 + html_s27 + html_s28 + html_s29 + html_s30 + slidescript;
var result = html;

var alt_html = html1 + html_css + html_evatop + alt_html_s1 + alt_html_s2 + alt_html_s3 + alt_html_s4 + alt_html_s5 + alt_html_s6 + alt_html_s7 + alt_html_s8 + alt_html_s9 + alt_html_s10 + alt_html_s11 + alt_html_s12 + alt_html_s13 + alt_html_s14 + alt_html_s15 + alt_html_s16 + alt_html_s17 + alt_html_s18 + alt_html_s19 + alt_html_s20 + alt_html_s21 + alt_html_s22 + alt_html_s23 + alt_html_s24 + alt_html_s25 + alt_html_s26 + alt_html_s27 + alt_html_s28 + alt_html_s29 + alt_html_s30 + slidescript;
var result2 = tidy_html5(alt_html, options);
